### ISSUE TITLE
動画構成

### ISSUE THREAD

**Issue by YukariHayashi** [furuhashilab/furuhashilab_movie_2024#4]
* [ ] 箇条書きテスト１
 * [ ] 箇条書きテスト２
 
```
 * [ ] 箇条書きテスト１
 * [ ] 箇条書きテスト２
```

**Comment by akidinosaurs** [comment]
7/16
 * [ ] 動画構成を確定する

* [x] ★今日のマスト
古橋さんへの質問＆インタビュー撮りきる
質問事項候補
1. ゼミの目的について
   - このゼミの目的は？
   - 学生に期待する成果や成長は？

2. ゼミの特徴と魅力
   - 古橋ゼミの1番の魅力は？
   - 他のゼミと比べてどのような点が異なる？

3. 具体的な活動内容
   - ゼミでは具体的にどのようなプロジェクトや活動を行っているのか
   - 学生が参加するプロジェクトの一例

4. 未来の展望
   - 今後ゼミをどのように発展させていきたいか
   - これからの新しい取り組みや計画は？

5. ゼミ生へのメッセージ
   - ゼミに参加を希望する学生に対してのアドバイス
   - 古橋ゼミでの経験を通して、どのようなスキルや価値観を身につけてほしいか


 * [ ] ★前提
ターゲット：古橋研の説明会に来た2年生
→全体的な概要を中心に話す
→詳細・READMEに記入済みの情報は省く
→ゼミ内サークル説明は短縮

 * [ ] ★動画編集の型
①テロップ
②ナレーションメイン
③テロップ+ナレーション複合
→作業時間を考慮して変更
→①＜③の順番で時間かかる

 * [ ] ★素材
[202407_古橋研究室紹介動画作成ハッカソン - ...FuruhashiLab - Google ドライブ](https://drive.google.com/drive/folders/1buICQUhZ9gaO5A8o_WeatAdo-0SCm5r-)
ここから取り出す
・合宿　（こうなが持ってる素材）
・イベント　（横瀬）
・作業風景
・授業風景
・＋a　上空写真とか？　空から相模原キャンパスにズームさせる

 * [ ] ★動画の流れ
制限時間3:00
約1分
00:01-00:50　ゼミ活動の紹介(合宿、UNmappar、国際会議)
約1分
00:51-02:10　ゼミ内サークルの紹介
約1分
02:11~03:00　古橋先生のコメント

 * [ ] プラン②　だいたい3:00くらい
 イントロ：約？分
コンテンツ候補1：　ゼミ活動の紹介(合宿、UNmappar、国際会議)
コンテンツ候補2：　ゼミ内サークル
〆：約1分　古橋先生のコメント
