### ISSUE TITLE
画像/動画の共有

### ISSUE THREAD

**Issue by YukariHayashi** [furuhashilab/furuhashilab_movie_2024#5]

**Comment by Kouna10** [comment]
動画のGoogle drive
https://drive.google.com/drive/u/1/folders/1buICQUhZ9gaO5A8o_WeatAdo-0SCm5r-

**Comment by Kouna10** [comment]
ゴールデンウィークの合宿の動画
https://drive.google.com/drive/u/1/folders/1buICQUhZ9gaO5A8o_WeatAdo-0SCm5r-

**Comment by Kouna10** [comment]
ゴールデンウィークの合宿の動画まとめ
https://drive.google.com/drive/folders/1buICQUhZ9gaO5A8o_WeatAdo-0SCm5r-?usp=drive_link

**Comment by Chisato111** [comment]
古橋先生へのインタビュー動画
https://drive.google.com/drive/folders/1-ZqZuMxtdpQ2OIsxBl0cQXRqeBJ01hCd?usp=drive_link
