### ISSUE TITLE
サークル内紹介素材デザイン・VF（みひろ）

### ISSUE THREAD

**Issue by YukariHayashi** [furuhashilab/furuhashilab_movie_2024#8]
- [ ] サークル内を紹介する素材をGoogleDriveにいれる
- [ ] サークル内のテロップとして紹介される質問を考え、それに対して15秒くらいで答える
- [ ] 顔アリで撮影

- [ ] その素材をGoogleDriveに入れる
- [ ] どんな質問項目にしたかはGitHubに記載しといてください！

- -Driveに入れるときのファイル名はほかのサークルと区別ができるように！
- ここにいれて！https://drive.google.com/drive/folders/1buICQUhZ9gaO5A8o_WeatAdo-0SCm5r-

**Comment by YukariHayashi** [comment]
@mihirotakiwaza 
質問項目何にしたかコメントで記入お願いします！

**Comment by mihirotakiwaza** [comment]
@YukariHayashi ごめん入力できてなかった！
デザイン-デザイン部について、デザイン部に向いている人は？
V&F-V&Fでできることは？

これで大丈夫？デザインだけ項目二つなってしまったごめん。
