### ISSUE TITLE
サークル内紹介素材Youth（まゆえいと）

### ISSUE THREAD

**Issue by YukariHayashi** [furuhashilab/furuhashilab_movie_2024#9]
- [x] サークル内を紹介する素材をGoogleDriveにいれる
- [ ] サークル内のテロップとして紹介される質問を考え、それに対して15秒くらいで答える
- [x] 顔アリで撮影
- [ ] その素材をGoogleDriveに入れる
- [ ] どんな質問項目にしたかはGitHubに記載しといてください！**

- -Driveに入れるときのファイル名はほかのサークルと区別ができるように！
- - ここにいれて！https://drive.google.com/drive/folders/1buICQUhZ9gaO5A8o_WeatAdo-0SCm5r-

**Comment by Mayukanazawa** [comment]
youth mappersは実際にはどんな活動をしていますか？
